import { Box, TextField, Button, Typography, Stack } from '@mui/material';
import { HeroSection } from 'astra';
import { FormLayout } from 'astra';
import { Card } from 'astra';

export const OnboardingRegistryApprovalContainer = () => {
  return (
    <Box sx={{ p: 4, width: '100%' }}>
      <HeroSection 
        headline="Registry Bootstrapping & Approval" 
        description="Define and approve the initial definitions for Virtual Employees, Skills, and Context Streams prior to permanent Vault commit."
      >
        <FormLayout title="Intent Ingestion" actions={<Button variant="contained">Generate Default Schema</Button>}>
          <Card supportingText="Provide raw text describing the organizational structure, constraints, and metrics.">
            <TextField 
              label="User Intent Input" 
              multiline 
              rows={4} 
              fullWidth 
              placeholder="e.g. We need two virtual employees capable of triaging security alerts and indexing knowledge base..." 
            />
          </Card>
        </FormLayout>
      </HeroSection>

      <Box sx={{ px: 4, mt: 2 }}>
        <Typography variant="h6" sx={{ mb: 2 }}>Schema Review & Override</Typography>
        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
            gap: 3,
          }}
        >
          <Box>
            <Card title="System-Generated Default Schema" supportingText="Read-only output generated by Goose logic model.">
              <Box sx={{ height: '300px', backgroundColor: 'background.default', borderRadius: 1, border: '1px solid', borderColor: 'divider', p: 2, overflowY: 'auto' }}>
                <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
                  {`// Awaiting Generation...`}
                </Typography>
              </Box>
            </Card>
          </Box>

          <Box>
            <Card title="User Variant (Edit Pipeline)" supportingText="Direct JSON/YAML edits or file uploads override the defaults.">
              <Box sx={{ height: '300px', backgroundColor: 'background.paper', borderRadius: 1, border: '1px dashed', borderColor: 'divider', p: 2, display: 'flex', flexDirection: 'column', gap: 2 }}>
                <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
                  {`// Override schema here...`}
                </Typography>
                <TextField multiline rows={8} fullWidth variant="standard" InputProps={{ disableUnderline: true }} />
              </Box>
              <Stack direction="row" spacing={2} sx={{ mt: 2 }}>
                <Button variant="outlined" component="label">
                  Upload .yaml
                  <input type="file" hidden accept=".yaml,.json" />
                </Button>
                <Button variant="contained" color="success">Submit for Approval</Button>
              </Stack>
            </Card>
          </Box>
        </Box>
      </Box>
    </Box>
  );
};
